backend:
  name: github
  repo: verythorough/docs-kit-hugo-learn
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "basics" # Used in routes, e.g. /admin/collections/blog
    label: "Basics" # Used in the UI
    folder: "content/basics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "In navigation?", name: "toc", widget: "boolean"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}